export const STATUS_REP_SUCCESS="STATUS_REP_SUCCESS"
export const STATUS_REP_LOADING="STATUS_REP_LOADING"
export const STATUS_REP_FAILURE="STATUS_REP_FAILURE"
export const GET_ALL_STATUS_REP_SUCCESS="GET_ALL_STATUS_REP_SUCCESS"
export const GET_ALL_STATUS_REP_LOADING="GET_ALL_STATUS_REP_LOADING"
export const GET_ALL_STATUS_REP_FAILURE="GET_ALL_STATUS_REP_FAILURE"

export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_LOADING="SIGNUP_LOADING"
export const SIGNUP_FAILED="SIGNUP_FAILED"

export const SIGNIN_SUCCESS="SIGNIN_SUCCESS"
export const SIGNIN_LOADING="SIGNIN_LOADING"
export const SIGNIN_FAILED="SIGNIN_FAILED"